{
  "formatVersion": "1.1",
  "component": {
    "group": "org.openstreetmap.josm.gradle-josm-plugin",
    "module": "dogfood",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.13.0.202109080827-r"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "dogfood-0.8.0.jar",
          "url": "dogfood-0.8.0.jar",
          "size": 106139,
          "sha512": "4cacf385853d25b4d8e1bdb20070fb8ca59a97fa0d91b87510b2b587b86251c9d90e86d4a34127caad1569776312d3ea648268314811c01eb8d098af695876e7",
          "sha256": "e40e49fb2e1bf477275839a0bf2f2868317bb5138e079bd6156cb5d40bd630f8",
          "sha1": "a01257ba5cfb84d8decb2949c53c5263fefe3d05",
          "md5": "b3150b7d0f2d3f5929da1de26c291f85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.13.0.202109080827-r"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "dogfood-0.8.0.jar",
          "url": "dogfood-0.8.0.jar",
          "size": 106139,
          "sha512": "4cacf385853d25b4d8e1bdb20070fb8ca59a97fa0d91b87510b2b587b86251c9d90e86d4a34127caad1569776312d3ea648268314811c01eb8d098af695876e7",
          "sha256": "e40e49fb2e1bf477275839a0bf2f2868317bb5138e079bd6156cb5d40bd630f8",
          "sha1": "a01257ba5cfb84d8decb2949c53c5263fefe3d05",
          "md5": "b3150b7d0f2d3f5929da1de26c291f85"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dogfood-0.8.0-javadoc.jar",
          "url": "dogfood-0.8.0-javadoc.jar",
          "size": 412062,
          "sha512": "afd25a4e5b190ce69a7b4541dcc032c1d6bf0d555807300d9f2702e90bef437a989a729b7b4e73557a312a82f2b90f8f71b826c500bf11c4ad1f7274a435ac54",
          "sha256": "f11339e3290b8f285584c90e07590a28000a454f15ec69324db3699f73344678",
          "sha1": "b885db3e769001443147b5b6aceb7f77ef885a55",
          "md5": "5b5b7b37f43d264f5c0484fef973358f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dogfood-0.8.0-sources.jar",
          "url": "dogfood-0.8.0-sources.jar",
          "size": 14946,
          "sha512": "66ceaa1446c384061cb599ad82e763f770ee3d7fa6f060e645ac51e4a458654903b52a2a9b506c4e5a3108f69d571dfca344090d744abd069e11c134ff57790b",
          "sha256": "7e0cf621de6f9f6934203d51f5e75b0bf6f698042fd6830f95c771ee2c3d73cf",
          "sha1": "76d7047c97e928626e2eb8bfcfbf45c5559e7e51",
          "md5": "d368d0bd7f8d8103014c7284b9d794c0"
        }
      ]
    }
  ]
}
